name: Camunda workflow Test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      bpmn_file_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Camunda file name'
        # Default value if no value is explicitly provided
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Zeebe client tools
        run: npm install -g zbctl

      - name: Upload BPMN artifact
        uses: actions/upload-artifact@v2
        with:
          name: bpmn-artifact
          path: ./bpmn

      - name: Deploy process to Camunda
        run: |
          zbctl deploy resource ${{ github.event.inputs.bpmn_file_name }}.bpmn --address 'd748db5f-f16e-4e50-9f85-c38423a8b8e0.syd-1.zeebe.camunda.io:443' --clientId 'hElxlz4k5mDNhbdCCTLWPpQ2ko8XEbBH' --clientSecret 'OQE24Q93o-BTYkfdg79QB.-Iyd_RAZoOkTcbxI4KyLe8Bie4kfbd98P52e~pN~Rt' --authorizationServerUrl 'https://login.cloud.camunda.io/oauth/token'
        working-directory: ./bpmn
