name: Camunda workflow Test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      bpmn_file_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Camunda file name'
        # Default value if no value is explicitly provided
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Zeebe client tools
        run: npm install -g zbctl

      - name: Upload BPMN artifact
        uses: actions/upload-artifact@v2
        with:
          name: bpmn-artifact
          path: ./bpmn

      - name: Deploy process to Camunda
        run: |
          zbctl deploy resource ${{ github.event.inputs.bpmn_file_name }}.bpmn --address 'http://10.10.102.86:30010' --clientId 'zeebe' --clientSecret 'test' --authzUrl 'http://10.10.102.86:30001/auth/realms/camunda-platform/protocol/openid-connect/token'
        working-directory: ./bpmn
