name: Camunda workflow Test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      bpmn_file_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Camunda file name'
        # Default value if no value is explicitly provided
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload BPMN artifact
        uses: actions/upload-artifact@v2
        with:
          name: bpmn-artifact
          path: ./bpmn

      - name: Deploy process to Camunda
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" \
          -F "deployment-name=${{ github.event.inputs.bpmn_file_name }}" \
          -F "enable-duplicate-filtering=true" \
          -F "deploy-changed-only=true" \
          -F "data=@./bpmn/${{ github.event.inputs.bpmn_file_name }}.bpmn" \
          https://caa5-2408-8340-1420-f1a0-6191-5b1c-df69-6348.ngrok-free.app/engine-rest/deployment/create
